name: Daily Submodule Update

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update submodules
        run: |
          git submodule foreach git pull origin master
          git add .
          git commit -m "AUTO SUBMODULES UPDATE" || echo "No changes to commit"
          git push origin master