name: Daily Submodule Update

on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.MY_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach "git checkout master; git fetch --all; git reset --hard origin/master; git clean -df"
          git add .
          git commit -m 'Updated submodules to latest commit' || echo 'No changes to commit'
          git push origin master