name: Submodule Update

on:
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 0-3,5-23 * * *'

jobs:
  force-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Git identity
        run: |
          git config --local user.name "melanieyanez"
          git config --local user.email "melanieyanez@gmail.com"

      - name: Force update submodules to the latest commit
        run: |
          git submodule update --init --recursive
          git submodule foreach "git checkout master; git fetch --all; git reset --hard origin/master; git clean -df"

      - name: Pull latest changes
        run: |
          git pull --rebase origin master

      - name: Commit changes
        run: |
          git commit -m "AUTO SUBMODULES UPDATE" --allow-empty

      - name: Push changes
        run: |
          git push origin master

  check-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Git identity
        run: |
          git config --local user.name "melanieyanez"
          git config --local user.email "melanieyanez@gmail.com"

      - name: Update submodules to the latest commit if changed
        run: |
          git submodule update --init --recursive
          git submodule foreach "git checkout master; git fetch --all; git reset --hard origin/master; git clean -df"

      - name: Pull latest changes
        run: |
          git pull --rebase origin master

      - name: Commit changes if there are any
        run: |
          git commit -m "AUTO SUBMODULES UPDATE" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin master