name: Daily Submodule Update

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.MY_TOKEN }}

      - name: Force update submodules to the latest commit
        run: |
          git submodule update --init --recursive
          git submodule foreach "git checkout master; git fetch --all; git reset --hard origin/master; git clean -df"
          git add .
  
      - name: Commit changes
        run: |
          git diff --cached --exit-code --quiet && COMMIT_MESSAGE="No changes in submodules detected" || COMMIT_MESSAGE="AUTO SUBMODULES UPDATE"
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push origin master